LOGGLY_TOKEN: "LOGGLY_TOKEN"
LOGZ_TOKEN: "LOGZ_TOKEN"
DATADOG_API_KEY: "DATADOG_API_KEY"
ROLLBAR_ACCESS_TOKEN: "ROLLBAR_TOKEN"
ROLLBAR_REPORT_LEVEL: "WARNING"
ENABLE_CLOUD_TRAIL_LOGGING: "false"
STAGE_TARGET: "false"
